name: Angular GitHub CI
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        working-directory: ./app-wasm
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

        
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Depedenceis NPM
        uses: actions/jekyll-build-pages@v1
        with:
          working-directory: ./app-wasm
          run: |
           npm run build:pages
      #- name: Build
      #  uses: actions/jekyll-build-pages@v1
      #  with:
      #    source: ./app-wasm
      #   destination: ./_site
      #- name: Upload artifact
      #  uses: actions/upload-pages-artifact@v1
    
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          working-directory: ./app-wasm
          github_access_token: ${{ secrets.GITHUB_TOKEN  }} 
          build_configuration: production 
          base_href: /webassembly-rust-wasm-callback/  
          deploy_branch: gh-pages 
          angular_dist_build_folder: dist/app-wasm
 
